[build]
builder = "DOCKERFILE"
buildCommand = "echo 'Building with Docker'"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[deploy.environmentVariables]]
name = "PORT"
value = "5000"

[[deploy.environmentVariables]]
name = "FLASK_ENV"
value = "production"